# Generated by Django 4.2.1 on 2023-08-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorcalendar',
            old_name='calendar_doctor',
            new_name='appointment',
        ),
        migrations.RenameField(
            model_name='patientcalendar',
            old_name='calendar_patient',
            new_name='appointment',
        ),
    ]
