# Generated by Django 4.2.1 on 2023-08-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_calendar_doctor_doctorcalendar_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcalendar',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='patientcalendar',
            name='patient',
        ),
        migrations.DeleteModel(
            name='DoctorCalendar',
        ),
        migrations.DeleteModel(
            name='PatientCalendar',
        ),
    ]
